import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.scss";
import { ModalProvider } from "../hooks/useModal";
import AppHeader from "../components/app-header";
import AppFooter from "../components/app-footer";
import AppContent from "../components/app-content";
import { AuthProvider } from "@/hooks/useAuth";
import Modal from "@/components/modal";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <ModalProvider>
          <div className="flex flex-col min-h-screen">
            <AuthProvider>
              <AppHeader />
              <AppContent>
                {children}
              </AppContent>
              <AppFooter />
            </AuthProvider>
            <Modal />
          </div>
        </ModalProvider>
      </body>
    </html>
  );
}
